export const products = [
  {
    id: 1,
    name: "SK & SKL Series",
    image: "/skseries/Skseries.png",
    description: "End Suction Centrifugal Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 270m³/hr",
        "Head (H)": "Max 102m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SK 3 / 2",
      "SK 4 / 3",
      "SKB 6 / 4",
      "SKL 2.5 / 1.5",
      "SKL 3 / 2",
      "SKL 4 / 3",
      "SKL 6 / 4",
    ],
  },
  {
    id: 2,
    name: "SKP SERIES",
    image: "/skseries/Skpseries.png",
    description: "Self-Priming Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 210m³/hr",
        "Head (H)": "Max 90m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "3 Pump Sizes",
      },
    ],
    applications: [
      "Waste Water",
      "Water Supply",
      "Fuel, Diesel & Light Oils",
    ],
    model: [
      "SKP 1.5",
      "SKP 2",
      "SKP 3",
    ],
  },
  {
    id: 3,
    name: "SKLB SERIES",
    image: "/skseries/Sklwseries.png",
    description: "Desander Centrifugal Pump",
    features: [
      "Handle Abrasive and Corrosive Pulp with Heavy Slurries",
      "Low Speed",
      "Hydraulic Design",
      "Interchangeability",
      "Heavy Duty Construction",
      "Low Operating Cost",
    ],
    technical: [
      {
        "Flow (Q)": "Max 110m³/hr",
        "Head (H)": "Max 60m",
        "Working Temperature": "80°C ~ 120°C",
        Bearing: "Heavy duty pedestal / Big bearing",
        "Impeller Diameter": "380mm - 'Closed' Type",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Contain",
      },
    ],
    applications: [
      "Feed Pump in Pre-Cleaner System",
      "Cleaning System for Oil and Gas Industries",
      "Sludge Thickening and Dewatering",
      "Waste Treatment",
      "Food and Chemical Industries",
      "Crude Palm Oil Industries",
    ],
    model: [
      "SKLB 40-380C",
    ],
  },
  {
    id: 4,
    name: "SKWT SERIES",
    image: "/skseries/Skwtseries.png",
    description: "End Suction Centrifugal Pump",
    features: [
      "Optimized hydraulics",
      "Easy maintenance",
      "Wide range",
      "High efficiency & reliability",
    ],
    technical: [
      {
        "Flow (Q)": "Max 480m³/hr @2900rpm",
        "Head (H)": "Max 100m @2900rpm/ Max45 @1450rpm",
        "Working Temperature": "95°C",
        Connection: "Flange(PN16)",
        Rotation: "Clockwise",
        Material: "Cast Iron / Stainless Steel 304 / 316",
      },
    ],
    applications: [
      "Raw Water Supply",
      "Drainage",
      "Pumping",
      "Heating & Ventilating",
      "Fire Fighting",
      "Water Treatment & Supply",
    ],
    model: [
      "SKWT 32-130 ~ 100-400",
    ],
  },
  {
    id: 5,
    name: "SKMS SERIES",
    image: "/skseries/SKMSseries.png",
    description: "Closed Coupled, Small Centrifugal Pump",
    features: [
      "Light Weight and Compact",
      "Safety and Reliable Operation",
      "Easy Installation and Maintenance",
      "Lower Cost",
    ],
    technical: [
      {
        "Flow (Q)": "4 - 10m³/hr",
        "Head (H)": "25m",
        "Working Temperature": "20°C ~ 120°C",
        "Inlet/Outlet": "40mm/40mm",
        Motor: "2hp @ 1450 / 2900 rpm",
      },
    ],
    applications: [
      "Water Supply",
      "Solid Handling in Industrial Waste Product",
      "Auxiliary Services in Chemical Industries",
      "Sewage Pumping",
      "Aggressive Liquid Applications",
      "Small Pond or Fountain",
      "Manure Handling in Agriculture",
    ],
    model: [
      "SKMS 1.5",
    ],
  },
  {
    id: 6,
    name: "SK 168 & 188D",
    image: "/skseries/ChemicalDosingPumpSK.png",
    description: "Chemical Dosing Pump",
    features: [
      "Flexibility",
      "Service-Friendly",
      "Wide Range",
      "High Accuracy",
    ],
    technical: [
      {
        "Flow (Q)": "Simplex 60 Ltr/hr, Duplex 120 Ltr/hr",
        Pressure: "Max 35kg/cm³",
        "Working Temperature": "80°C ~ 120°C",
        "Suction Lift": "Max 3mm for Water",
      },
    ],
    applications: [
      "Water Treatment",
      "Wastewater Treatment",
      "Acids",
      "Cosmetics",
      "Food Ingredients",
      "Chemical Additive",
      "Soap Lubricant",
    ],
    model: [
      "SK 168S / D",
      "SK 188S / D",
      "SK 268S / D",
      "SK 288S / D",
    ],
  },
  {
    id: 7,
    name: "SK 368 SERIES",
    image: "/skseries/ChemicalDiaphragmPumpSK368Series.png",
    description: "Chemical Diaphragm Pump",
    features: [
      "Minimal Maintenance ",
      "High Performance",
      "Low Lifecycle Cost",
      "Long Life Span",
    ],
    technical: [
      {
        "Capacity Range": "10 1ph - 1000 1ph under 50HZ",
        "Pressure Range": "2 - 10 bar",
        "Working Temperature": "30°C ~ 80°C",
        "Stoke Adjustment": "0 ~ 100%",
      },
    ],
    applications: [
      "Heavy-duty Designed Process Pump for Chemical Dosing",
      "Waste Treatment", 
      "Industrial Chemical Process", 
      "Agriculture",
    ],
    model: [
      "SK 368-120",
      "SK 368-240",
      "SK 368-400",
      "SK 368-600",
      "SK 368-1000",
    ],
  },
  {
    id: 8,
    name: "SKVSP SERIES",
    image: "/skseries/VerticalSumpPumpSKVSPSeries.png",
    description: "Vertical Sump Pump",
    features: [
      "Single Stage Centrifugal Sump Pump",
      "Transferring and Handling of Sediment, Sludge, Scale, Slurries",
      "Fully Stainless Steel Constructed for Corrosion Resistant",
      "Adjustable Submerged Dephs",
      "Double Bearing at Frame Adaptor",
    ],
    technical: [
      {
        "Flow (Q)": "Max 250m³/hr",
        "Head (H)": "Max 22m",
        "Solid Size": "Max 30mm",
        "Impeller Type": "Semi-Open",
        "Submerged Column": "1m",
        "Non-submerged Column": "0.50m",
        "Shaft": "Rigid 38mm Dynamically Balance",
        "Shaft Sleeve / Grand Packed": "Stainless Steel and Media Lubricated",
        "Bearing": "Double Bearing at Frame Adaptor",
      },
    ],
    applications: [
      "Palm Oil Mill Pit and Pond",
      "Sump drainage",
      "Food Control",
      "Power Plants",
      "Condensation control",
      "Dewatering Service",
    ],
    model: [
      "SKVSP 2.5 / 1.5",
      "SKVSP 3 / 2",
      "SKVSP 4 / 3",
      "SKVSP 5 / 4R",
    ],
  },
  {
    id: 9,
    name: "PRE-CLEANER SYSTEM",
    image: "/skseries/PreCleanerSystem.png",
    description: "SK PRE-CLEANER WITH AUTO DISCHARGE SYSTEM",
    features: [
      "Components Made in Wear Resistant Material",
      "High Abrasive Resistance Ceramic Cyclone",
      "High Efficiency of Sand Removal",
      "Negligible Starch Loss Due to Upstream Water",
      "Automatic Sand Discharge",
    ],
    technical: [
      {
        "Cyclone Diameter": "100 ~ 150mm",
        "Capacity": "15.0 ~ 30.0m³/hr",
        "Equivalent Milling Capacity": "30 ~ 60 mt  FFB/hr",
      },
    ],
    applications: [
      "Trap Sand and Particle from Different Liquid or Process Water such as Crude Palm Oil and Sludge Waster",
    ],
    model: [
      "100-30S",
      "100-30D",
      "150-45S",
      "150-60S",
    ],
  },
  {
    id: 10,
    name: "SKOSP SERIES",
    image: "/skseries/SKOSPSeries.png",
    description: "OIL SKIMMER PUMP",
    features: [
      "Simple, Proven & Dependable Design",
      "Quick & Easy Installation",
      "Self-adjusting to Changing Wastewater Level",
      "Simple & Compact Structure",
    ],
    technical: [
      {
        "Flow (Q)": "5m³/hr or 1000L/hr",
        "Priming Head": "10m",
        "Lift Head": "20m",
        "Speed": "1450 rpm",
      },
    ],
    applications: [
      "Oily Wastewater Industrial Operations",
      "Fuel Distribution Areas",
      "Chemical Processing Facilities",
      "Transportation Wash-down Sump",
    ],
    model: [
      'SKOSP 1"',
    ],
  },
  {
    id: 11,
    name: "SK MIXER SERIES",
    image: "/skseries/SKMixerSeries.png",
    description: "SK MIXER & AGITATOR",
    features: [
      "Continuous Operations is Possible",
      "Space Saving, Light Weight and Easy Installations & Maintenance",
      "Low Operations Cost",
      "Stable Performance, Low Noise and Low Vibrations",
      "Long Lift Span of Gear Motor and Support Bearing",
    ],
    technical: [
      {
        "Flow (Q)": "Low Viscosity: 1250 Ltr, Medium Viscosity: 400 Ltr",
        "Input Power": "0.37 kw/0.5 hp 415V",
        "Resolutions": "295 rpm",
        "Shaft Diameters": "16mm",
        "Impeller Diameters": "200mm",
      },
    ],
    applications: [
      "Used for rapid mixing, neutralizations in",
      "Chemical Industries",
      "Waste Water Industries",
      "Food Processing",
      "Agriculture",
    ],
    model: [
      "SK 1250",
    ],
  },
  {
    id: 12,
    name: "VC SERIES",
    image: "/skeroseries/VCSeries.png",
    description: "LIQUID RING VACUUM PUMP",
    features: [
      "Efficient Single Stage Design",
      "Low Maintenance Required",
      "Low Noise & Vibration Levels",
      "Entrained Liquid Handling",
    ],
    technical: [
      {
        "Flow (Q)": "180 ~ 600m³/hr",
        "Head (H)": 'Max 27"hg',
        "Working Temperature": "Service Liquid(80°C ~ 120°C), Gas(Max 100°C)",
        "Sealing": "Mechanical Seal",
        "Viscosity": "Max 90 mm²/s",
        "Flow Resistance of Heat Exchanger": "Max 0.2 bar",
      },
    ],
    applications: [
      "Drying",
      "Distillation",
      "Evaporation Crystallization",
      "Vapor Recovery",
      "Sterilization",
      "Filtration",
      "Vacuum Conveyance",
      "Priming",
      "Central Vacuum Systems",
    ],
    model: [
      "VC 40-160",
      "VC 50-120",
      "VC 50-160",
      "VC 50-200",
      "VC 65-200",
      "VC 65-266",
    ],
  },
  {
    id: 13,
    name: "BF SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "MULTI STAGE BOILER FEED WATER PUMP",
    features: [
      "High Efficiency",
      "Low Energy Consumption",
      "Longer Life",
      "Advanced Modular Design",
    ],
    technical: [
      {
        "Flow (Q)": "Max 110m³/hr",
        "Head (H)": "Max 395m",
        "Working Temperature": "Max 194°C",
        "Shaft Sealing": "Gland  Packing or Mechanical Seal",
        "Sense of Rotation": "Clockwise, when Viewed from Discharge Side",
      },
    ],
    applications: [
      "Boiler Feed",
      "Pressure Boosting",
      "High Pressure Cleaning",
      "Condensate Systems",
      "Chemical & Process",
      "Irrigation of Plant",
      "Heating Plant",
      "Reverse Osmosis",
      "Water Supply in High-rise Building",
    ],
    model: [
      "BF 40-",
      "BF 50-",
      "BF 65-",
    ],
  },
  {
    id: 14,
    name: "OT SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "SIDE CHANNEL OIL TRANSFER PUMP",
    features: [
      "Self-priming",
      "Gas Handling",
      "Ability to Handle Liquid Problem-free under Unfavourable Conditions",
      "Low NPSH Value",
    ],
    technical: [
      {
        "Flow (Q)": "Max 35m³/hr",
        "Head (H)": "Max 354m",
        "Speed": "Max 1800 rpm",
        "Working Temperature": "180°C",
        "Casing Pressure": "PN 40",
        "Shaft Sealing": "Gland Packing / Mechanical Seal",
        "Flange Connection": "DIN 2501 PN 40",
        "Sense of Rotation": "Anti-Clockwise",
      },
    ],
    applications: [
      "Condensate",
      "Distillation",
      "Refrigerants",
      "Oil Transfer",
      "Fuel Storage",
      "Liquid Gas",   
    ],
    model: [
      "OT 40-",
      "OT 50-",
      "OT 65-",
    ],
  },
  {
    id: 15,
    name: "DT SERIES",
    image: "/skeroseries/DTSeries.png",
    description: "VOLUTE CASING DEAERATOR PUMP",
    features: [
      "Non-clogging Design",
      "Suitable for Higher Flow per Pump",
      "Reliability & High Efficiency",
      "Simple Maintenance",
    ],
    technical: [
      {
        "Flow (Q)": "Max 110m³/hr",
        "Head (H)": "Max 395m",
        "Speed": "Max 3000 rpm",
        "Working Temperature": "120°C",
        "Casing Pressure": "PN 16/10",
        "Shaft Sealing": "Mechanical Seal",
        "Flange Connection": "DIN 2501 PN 16/10",
        "Sense of Rotation": "Clockwise, when Viewed from the Driver End",
      },
    ],
    applications: [
      "Drinking Water Supply for Communities",
      "General Water Supply in Agriculture, Business & Industry",
      "Draining of Tanks & Reservoirs",
      "Irrigation, sprinking & drainage systems",
      "Condense Water Pumping",
      "Petrochemical Sector",
      "Handling Crude Oil & Refinery Intermediates",
    ],
    model: [
      "DT 65-250",
      "DT 80-250",
    ],
  },
  {
    id: 16,
    name: "WOLTMAN FLOWMETER",
    image: "/setech/WoltmanFlowmeter.png",
    description: "COLD WATER HORIZONTAL WOLTMAN FLOWMETER",
    features: [
      "Easy Installation and Maintenance",
      "Dry-dial, Magnetic Drive Sensitive Action, Small Pressure Loss",
      "Vacuum Sealed Register, Free from Fog and Clear Reading",
      "High Quality Materials",
      "International Standard ISO 4064",
    ],
    technical: [
      {
        "Working Temperature": "0.1°C ~ 40°C, Hot Water Meter(0.1°C ~ 90°C)",
        "Water Pressure": "≤ 1.6Mpa",
        "Maximum Permissible Errors": "Lower Zone from qmin inclusive up to but excluding qt is ±5%, Upper Zone from qt inclusive up to and including qs is ±2% (±3% for Hot Water Meter)",
      },
    ],
    applications: [
      "Measuring the Volume of Cold/Hot Waterpassing through the Pipeline",
    ],
    model: [
      "HGLC-50",
      "HGLC-65",
      "HGLC-80",
      "HGLC-100",
      "HGLC-125",
      "HGLC-150",
      "HGLC-200",
      "HGLC-250",
      "HGLC-300",
    ],
  },
  {
    id: 17,
    name: "ELECTROMAGNETIC FLOWMETER",
    image: "/setech/ElectromagneticFlowmeter.png",
    description: "ELECTROMAGNETIC FLOWMETER",
    features: [
      "Long Operation Life",
      "No Intercepting Fluid Parts",
      "No Pressure Loss and Fluid Clogging",
      "Adopt EEPROM Memory",
      "Integral Type Flow Meters & Remote Type Flow Meters",
      "LCD Back Light Display",
      "Bi-direction Measurement (Option)",
      'Aproved from CE, EMC, ISO',
      'Programming Language: English',
    ],
    technical: [
      {
        "Suitable Diameter": "DN25 ~ DN2600 (below DN25 Non-standard)",
        "Electrode No.": "2 ~ 3pcs",
        "Min Conductivity": "More than 5 Microsimens",
        "Measuring Range": "0.5 ~ 10m/s (extendable to 15m/s)",
        "Upper Limit of Span": "0.5 ~ 10m/s, 1 ~ 5m/s Recommended ",
        "Accuracy": "0.3%(Option), 0.5%, 1.0% of F.S.",
        "Repeatability": "Below 0.25%",
        'Power Consumption': "≤ 8W",
        'Operation Pressure': '1.0MPa, 1.6MPa, 4.0MPa, 16Mpa(Special)',
        'Fluid Temperature': "-20°C ~ 80°C, 80°C ~ 130°C, 130°C ~ 180°C Depending on Lining Material",
        'Quality Control': 'ISO9001-2008, CE',
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SE-HGD-15 ",
      "SE-HGD-20 ",
      "SE-HGD-25 ",
      "SE-HGD-32 ",
      "SE-HGD-40 ",
      "SE-HGD-50 ",
      "SE-HGD-65 ",
      "SE-HGD-80 ",
      "SE-HGD-100 ",
      "SE-HGD-125 ",
      "SE-HGD-150 ",
      "SE-HGD-200 ",
      "SE-HGD-250 ",
      "SE-HGD-300 ",
      "SE-HGD-350 ",
      "SE-HGD-400 ",
      "SE-HGD-450",
      "SE-HGD-500",
      "SE-HGD-600",
      "SE-HGD-700",
      "SE-HGD-800",
      "SE-HGD-1000",
      "SE-HGD-1200",
      "SE-HGD-1400",
      "SE-HGD-1600",
      "SE-HGD-1800",
      "SE-HGD-2000",
      "SE-HGD-2200",
      "SE-HGD-2400",
      "SE-HGD-2600",
    ],
  },
  {
    id: 18,
    name: "FLOWMETER CONTROLLER",
    image: "/setech/FlowmeterController.png",
    description: "FLOWMETER CONTROLLER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 19,
    name: "NUT CRACKER",
    image: "/setech/NutCracker.png",
    description: "NUT CRACKER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Capacity": "8mt/hr",
        "Rotor Support": "Heavy Duty Plummer Block Bearing at Both Ends",
        "Motor": "20Hp(15kw) 380-420v/3ph/50Hz/4pole Foot Mounted",
        "Drive": 'SPB 3 x7" and 11" Taper Lock Pulley and Belting c/w Belting Cover',
        "Base Frame": "50 x 100mm Channel",
        "Performance" : "Cracking Efficiency of > 98%",
      },
    ],
    applications: [
      "Palm Oil",
    ],
    model: [
      "SE-8MT",
    ],
  },
  {
    id: 20,
    name: "GAS DETECTOR",
    image: "/setech/GasDetector.png",
    description: "GAS DETECTOR",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 21,
    name: "ULTRASONIC THICKNESS GAUG",
    image: "/setech/UltrasonicGauge.png",
    description: "ULTRASONIC THICKNESS GAUG",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 22,
    name: "CONVEYOR CHAIN",
    image: "/trp/PalmOilChain.png",
    description: "CONVEYOR CHAIN",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Breaking Load (SIRIM Test)": "SOLID Pin Chain(44000 ~ 81000lbf), HOLLOW Pin Chain(27000 ~ 59000lbf)",
        "Pitch(P)": "101.60mm & 152.40mm",
        "Roller Diameter(D)": "47.60mm & 66.70mm",
        "Pin Diameter(D)": "SOLID Pin Chain(19.00mm & 27.00mm), HOLLOW Pin Chain(13.20mm & 20.10mm)",
        "Plate Height": "38.10mm & 50.80mm",
      },
    ],
    applications: [
      "Palm Oil Industry",
    ],
    model: [
      "Solid Pin Chain (SPC)",
      "TRP SM220040",
      "TRP SM400060",
      "TRP SM600060",
      "Hollow Pin Chain (HPC)",
      "TRP HM200040",
      "Trp HM360060",
      "Trp HM500060",
    ]
  },
  {
    id: 23,
    name: "SPROCKETS",
    image: "/trp/Sprockets.png",
    description: "SPROCKETS",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Material": "Cast Iron / Cast Steel",
        "No. of Teeth": "8 ~ 21",
      },
    ],
    applications: [
      "Palm Oil Industry",
    ],
    model: [
      "Chain Pitch 101.6",
      "Chain Pitch 152.4",
    ],
  },
  {
    id: 24,
    name: "MC SERIES",
    image: "/seweurodrive/MCSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Mechanical Power Rating(kW)": "46.3 ~ 72.7(@n1 = 1500rpm)",
        "Mechanical Torque Rating(kNm)": "16.6 ~ 24.9(@n1 = 1500rpm)",
        "Exact Ratio": "57.962, 55.740, 56.313",
        "Speed(n1/n2)": "1500/25.9, 1500/26.6, 1500/26.9",
        "Weight(Kg)": "396 ~ 614",
        "Quality of Oil(l)": "45, 58, 73",
      },
    ],
    applications: [
      "Palm Oil Mill",
    ],
    model: [
      "Gear Unit MC3PVSF04",
      "Gear Unit MC3PVSF05",
      "Gear Unit MC3PVSF06",
    ],
  },
  {
    id: 25,
    name: "M SERIES",
    image: "/seweurodrive/MSeries.png",
    description: "KERNEL EXPELLER DRIVES",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Mechanical Power Rating(kW)": "136 ~ 254(@n1 = 1000rpm), 102 ~ 191(@n1 = 750rpm)",
        "Mechanical Torque Rating(kNm)": "72 ~ 138(@n1 = 1000 & 750rpm)",
        "Exact Ratio": "55.438, 55.472, 55.959 &  56.686",
        "Speed(n1/n2)": "1000/18, 1000/17.9, 1000/17.6, 750/13.5, 750/13.4, 750/13.2",
        "Weight(Kg)": "1135 ~ 2100",
        "Quality of Oil(l)": "75, 83, 100, 125, 160",
      },
    ],
    applications: [
      "Palm Oil Mill",
    ],
    model: [
      "Gear Unit M3PSF60KPD",
      "Gear Unit M3PSF60POM",
      "Gear Unit M3PSF65POM",
      "Gear Unit M3PSF70POM",
      "Gear Unit M3PSF80POM",
    ],
  },
  {
    id: 26,
    name: "CN SERIES",
    image: "/seweurodrive/CNSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Mechanical Power Rating(kW)": "72(@n1 = 1500rpm)",
        "Mechanical Torque Rating(kNm)": "26(@n1 = 1500rpm)",
        "Exact Ratio": "57.328",
        "Speed(n1/n2)": "1500/26.2",
        "Weight(Kg)": "870",
        "Quality of Oil(l)": "94",
      },
    ],
    applications: [
      "Palm Oil Mill",
    ],
    model: [
      "Gear Unit 3PC250POM",
    ],
  },
  {
    id: 27,
    name: "R SERIES",
    image: "/seweurodrive/RSeries.png",
    description: "HELICAL GEAR MOTORS",
    features: [
      "Long Term Operation",
      "Precision-balanced and Low-noise",
      "High Gear Unit Efficiency",
      "High Torgues and Permitted Overhung Loads",
      "Transmission Gear for Multi-stage Gear Units"
    ],
    technical: [
      {
        "Max Torque(Nm)": "50 ~ 18000",
        "Pmmax(kW)": "0.37 ~ 160",
        "Exact Ratio": "???",
        "Speed(n1/n2)": "???",
        "Weight(Kg)": "???",
        "Quality of Oil(l)": "???",
      },
    ],
    applications: [
      "Conveyor",
      "Nut Polishing Drum",
    ],
    model: [
      "R 07",
      "R 17",
      "R 27",
      "R 37",
      "R 47",
      "R 57",
      "R 67",
      "R 77",
      "R 87",
      "R 97",
      "R 107",
      "R 137",
      "R 147",
      "R 167",
    ],
  },
  {
    id: 28,
    name: "M SERIES SCREW PRESS DRIVE",
    image: "/seweurodrive/MSeriesScrew.png",
    description: "SCREW PRESS DRIVE",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Mechanical Power Rating(kW)": "58 ~ 139(@n1 = 1000rpm), 44 ~ 105(@n1 = 750rpm)",
        "Mechanical Torque Rating(kNm)": "44 ~ 75(@n1 = 1000 & 750rpm)",
        "Exact Ratio": "55.391, 78.456, 55.438, 77.373",
        "Speed(n1/n2)": "1000/18, 1000/12.7, 1000/12.9, 750/13.5, 750/9.6, 750/9.56, 750/9.69",
        "Weight(Kg)": "768 ~ 1200",
        "Quality of Oil(l)": "55, 57, 75, 83",
      },
    ],
    applications: [
      "Palm Oil Mill",
    ],
    model: [
      "Gear Unit M3PSF50SPD",
      "Gear Unit M3PSF60SPD",
      "Gear Unit M3PSF50POM",
      "Gear Unit M3PSF60POM",
    ],
  },
  {
    id: 29,
    name: "ME SERIES",
    image: "/motology/motology.png",
    description: "THREE-PHASE ASYNCHRONOUS MOTOR",
    features: [
      "Water Dust and Vermin Resistant",
      "Heavy Duty Ball Bearing",
      "High Quality Magnet Wire",
      "Continuos S1 Duty",
      "Low Noise",
      "Corrosion Resistant",
      "Suitable for Most Environment",
      "Very Low Vibration",
      "Very Low Power Consumption",
      "Reliable and Longer Motor Life Span",
    ],
    technical: [
      {
        "Housing": "Cast Iron Housing",
        "Energy Efficient Class": "EFF2",
        "Power Factor":"0.61 ~ 0.92",
        "Output(kW)": "0.37 ~ 315",
        "Speed(rpm)": "680 ~ 2980",
        "Torque(Nm)": "1.3 ~ 2583",
        "Net Weight(Kg)":"8 ~ 1740",
      },
    ],
    applications: [
      "Agricultural",
      "Pumping",
      "Manufacturing",
      "Building Services"
    ],
    model: [
      "ME71A-2, ME71A-6",
      "ME71B-2, ME71B-4",
      "ME80A-2, ME80A-4, ME80A-6, ME80A-8",
      "ME80B-2, ME80B-4, ME80B-6",
      "ME90S-2, ME90S-4, ME90S-6, ME90S-8",
      "ME90L-2, ME90L-4, ME90L-6, ME90L-8",
      "ME100L-2, ME100L-6",
      "ME100LA-4, ME100LA-8",
      "ME100LB-4, ME100LB-8",
      "ME112M-2, ME112M-4, ME112M-6, ME112M-8",
      "ME132SA-2, ME132SB-2",
      "ME132S-4, ME132S-6, ME132S-8",
      "ME132M-4, ME132M-8",
      "ME132MA-6, ME132MB-6",
      "ME160M-4, ME160M-6",
      "ME160MA-2, ME160MA-8",
      "ME160MB-2, ME160MB-8",
      "ME160L-2, ME160L-4, ME160L-6, ME160L-8",
      "ME180M-2, ME180M-4",
      "ME180L-6, ME180L-8",
      "ME200L-4, ME200L-8",
      "ME200LA-2, ME200LA-6",
      "ME200LB-2, ME200LB-6",
      "ME225M-2, ME225M-4, ME225M-6, ME225M-8",
      "ME225S-4, ME225S-8",
      "ME250M-2, ME250M-4, ME250M-6, ME250M-8",
      "ME280S-2, ME280S-4, ME280S-6, ME280S-8",
      "ME280M-2, ME280M-4, ME280M-6, ME280M-8",
      "ME280MB-2, ME280MB-4",
      "ME315S-2, ME315S-4, ME315S-6, ME315S-8",
      "ME315M-2, ME315M-4, ME315M-6, ME315M-8",
      "ME315LA-2, ME315LA-4, ME315LA-6, ME315LA-8",
      "ME315LB-2, ME315LB-4, ME315LB-6, ME315LB-8",
      "ME355M-2, ME355M-4",
      "ME355MA-6, ME355MA-8",
      "ME355MB-6, ME355MB-8",
      "ME355L-2, ME355L-4, ME355L-6, ME355L-8"
    ],
  },
  {
    id: 30,
    name: "MEA SERIES",
    image: "/motology/motology.png",
    description: "THREE-PHASE ASYNCHRONOUS MOTOR",
    features: [
      "Water Dust and Vermin Resistant",
      "Universal Mounting",
      "Strengthen Cable Gland",
      "Continuos S1 Duty",
      "High Performance and Efficiency",
      "Low Noise & Vibration",
      "Corrosion Resistant",
      "Suitable for Most Environment",
      "Easy Installation",
      "Low Electrical Consumption",
      "Reliable and Longer Motor Life Span",
    ],
    technical: [
      {
        "Housing": "Aluminium Housing",
        "Energy Efficient Class": "EFF2",
        "Power Factor":"0.61 ~ 0.88",
        "Output(kW)": "0.18 ~ 7.5",
        "Speed(rpm)": "680 ~ 2900",
        "Torque(Nm)": "0.6 ~ 54.7",
        "Net Weight(Kg)":"4 ~ 54.5",
      },
    ],
    applications: [
      "For All General Purpose Drive and Industry",
    ],
    model: [
      // "2 Pole(-2): 3000 RPM",
      // "4 Pole(-4): 1500 RPM",
      // "6 Pole(-6): 1000 RPM",
      // "8 Pole(-8): 800 RPM",
      "MEA63A-2, MEA63B-4",
      "MEA71A-2, MEA71A-6",
      "MEA71B-2, MEA71B-4",
      "MEA80A-2, MEA80A-4, MEA80A-6, MEA80A-8",
      "MEA80B-2, MEA80B-4, MEA80B-6",
      "MEA90S-2, MEA90S-4, MEA90S-6, MEA90S-8",
      "MEA90L-2, MEA90L-4, MEA90L-6, MEA90L-8",
      "MEA100L-2, MEA100L-6",
      "MEA100LA-4, MEA100LA-8",
      "MEA100LB-4, MEA100LB-8",
      "MEA112M-2, MEA112M-4, MEA112M-6, MEA112M-8",
      "MEA132S-4, MEA132S-6, MEA132S-8",
      "MEA132SA-2, MEA132SB-2",
      "MEA132M-4, MEA132M-8",
      "MEA132MA-6, MEA132MB-6",
    ],
  },
  {
    id: 31,
    name: "MEB SERIES",
    image: "/motology/motology.png",
    description: "THREE-PHASE ASYNCHRONOUS BRAKING MOTOR",
    features: [
      "Water Dust and Vermin Resistant",
      "Universal Mounting",
      "Strengthen Cable Gland",
      "Continuos S1 Duty",
      "High Performance and Efficiency",
      "Low Noise & Vibration",
      "Corrosion Resistant",
      "Suitable for Most Environment",
      "Easy Installation",
      "Low Electrical Consumption",
      "Reliable and Longer Motor Life Span",
    ],
    technical: [
      {
        "Housing": "Aluminium Housing",
        "Energy Efficient Class": "EFF2",
        "Power Factor":"0.64 ~ 0.90",
        "Power(kW)": "0.12 ~ 22",
        "Speed(rpm)": "720 ~ 2970",
        "Static Braning Torque(Nm)": "4 ~ 200",
        "No-lod Brake Lag Time(s)":"0.20 ~ 0.35",
      },
    ],
    applications: [
      "Suitable for Any Machines that Require to Stop Quickly, Located Accurately, Rotating and Brake Frequently such as:",
      "Machine Tools",
      "Packing Machinery",
      "Wood Worker Machinery",
      "Food Processing Machinery",
      "Chemical Engineering Machinery",
      "Textile Machinery",
      "Construction Machinery",
      "Gear Reducer",
    ],
    model: [
      "MEB6312, MEB6314, MEB6322, MEB6324",
      "MEB7112, MEB7114, MEB7122, MEB7124",
      "MEB8012, MEB8014, MEB8022, MEB8024",
      "MEB90S-2, MEB90S-4, MEB90S-6",
      "MEB90L-2, MEB90L-4, MEB90L-6",
      "MEB100L-2, MEB100L-6",
      "MEB100L1-4, MEB100L2-4",
      "MEB112M-2, MEB112M-4, MEB112M-6",
      "MEB132S-4, MEB132S-6, MEB132S-8",
      "MEB132S1-2, MEB132S2-2",
      "MEB132M-4, MEB132M-8",
      "MEB132M1-6, MEB132M2-6",
      "MEB160M-2, MEB160M-4, MEB160M-6",
      "MEB160M1-8, MEB160M2-8",
      "MEB160L-2, MEB160L-4, MEB160L-6, MEB160L-8",
      "MEB180M-2, MEB180M-4",
      "MEB180L-2, MEB180L-4, MEB180L-6, MEB180L-8",
    ],
  },
  {
    id: 32,
    name: "MEY SERIES",
    image: "/motology/motology.png",
    description: "SINGLE-PHASE CAPACITOR RUN ASYNCHRONOUS MOTORS",
    features: [
      "High Performance and Efficiency",
      "Low Noise and Vibration",
      "Reliable and Longer Motor Life Span",
    ],
    technical: [
      {
        "Housing": "Aluminium Housing",
        "Power Factor": "0.92 ~ 0.95",
        "Power(kW)": "0.18 ~ 1.50",
        "Voltage(V)": "220",
        "Speed(rpm)": "1400 ~ 2800",
        "Net Weight(Kg)": "3.9 ~ 16",
      },
    ],
    applications: [
      "Suitable for Applications with Low Starting Torque",
    ],
    model: [
      "MEY631-2, MEY631-4, MEY632-2, MEY632-4, MEY711-2, MEY711-4, MEY712-2, MEY712-4, MEY801-1, MEY801-4, MEY802-2, MEY802-4, MEY90S-2, MEY90S-4, MEY90L-2, MEY90L-4",
    ],
  },
  {
    id: 33,
    name: "MEL SERIES",
    image: "/motology/motology.png",
    description: "SINGLE-PHASE DUAL CAPACITOR RUN ASYNCHRONOUS MOTORS",
    features: [
      "High Performance and Efficiency",
      "Low Noise and Vibration",
      "Reliable and Longer Motor Life Span",
    ],
    technical: [
      {
        "Housing": "Aluminium Housing",
        "Energy Efficient Class": "EFF2",
        "Power Factor": "0.92 ~ 0.95",
        "Power(kW)": "0.37 ~ 2.20",
        "Voltage(V)": "220",
        "Speed(rpm)": "1400 ~ 2800",
        "Net Weight(Kg)": "6.9 ~ 23",
      },
    ],
    applications: [
      "Suitable for Applications with High Starting Torque",
    ],
    model: [
      "MEL711-2, MEL711-4, MEL712-2, MEL712-4, MEL801-1, MEL801-4, MEL802-2, MEL802-4, MEL90S-2, MEL90S-4, MEL90L-2, MEL90L-4, MEL100L-2, MEL100L-4",
    ],
  },
  {
    id: 30,
    name: "BALL VALVE",
    image: "/valve/BallValve3.png",
    description: "1PC / 3PC BODY BALL VALVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
];
