export const products = [
  {
    id: 1,
    name: "SK & SKL Series",
    image: "/skseries/Skseries.png",
    description: "End Suction Centrifugal Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 270m³/hr",
        "Head (H)": "Max 102m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SK 3 / 2",
      "SK 4 / 3",
      "SKB 6 / 4",
      "SKL 2.5 / 1.5",
      "SKL 3 / 2",
      "SKL 4 / 3",
      "SKL 6 / 4",
    ],
  },
  {
    id: 2,
    name: "SKP SERIES",
    image: "/skseries/Skpseries.png",
    description: "Self-Priming Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 210m³/hr",
        "Head (H)": "Max 90m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "3 Pump Sizes",
      },
    ],
    applications: [
      "Waste Water",
      "Water Supply",
      "Fuel, Diesel & Light Oils",
    ],
    model: [
      "SKP 1.5",
      "SKP 2",
      "SKP 3",
    ],
  },
  {
    id: 3,
    name: "SKLB SERIES",
    image: "/skseries/Sklwseries.png",
    description: "Desander Centrifugal Pump",
    features: [
      "Handle Abrasive and Corrosive Pulp with Heavy Slurries",
      "Low Speed",
      "Hydraulic Design",
      "Interchangeability",
      "Heavy Duty Construction",
      "Low Operating Cost",
    ],
    technical: [
      {
        "Flow (Q)": "Max 110m³/hr",
        "Head (H)": "Max 60m",
        "Working Temperature": "80°C ~ 120°C",
        Bearing: "Heavy duty pedestal / Big bearing",
        "Impeller Diameter": "380mm - 'Closed' Type",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Contain",
      },
    ],
    applications: [
      "Feed Pump in Pre-Cleaner System",
      "Cleaning System for Oil and Gas Industries",
      "Sludge Thickening and Dewatering",
      "Waste Treatment",
      "Food and Chemical Industries",
      "Crude Palm Oil Industries",
    ],
    model: [
      "SKLB 40-380C",
    ],
  },
  {
    id: 4,
    name: "SKWT SERIES",
    image: "/skseries/Skwtseries.png",
    description: "End Suction Centrifugal Pump",
    features: [
      "Optimized hydraulics",
      "Easy maintenance",
      "Wide range",
      "High efficiency & reliability",
    ],
    technical: [
      {
        "Flow (Q)": "Max 480m³/hr @2900rpm",
        "Head (H)": "Max 100m @2900rpm/ Max45 @1450rpm",
        "Working Temperature": "95°C",
        Connection: "Flange(PN16)",
        Rotation: "Clockwise",
        Material: "Cast Iron / Stainless Steel 304 / 316",
      },
    ],
    applications: [
      "Raw Water Supply",
      "Drainage",
      "Pumping",
      "Heating & Ventilating",
      "Fire Fighting",
      "Water Treatment & Supply",
    ],
    model: [
      "SKWT 32-130 ~ 100-400",
    ],
  },
  {
    id: 5,
    name: "SKMS SERIES",
    image: "/skseries/SKMSseries.png",
    description: "Closed Coupled, Small Centrifugal Pump",
    features: [
      "Light Weight and Compact",
      "Safety and Reliable Operation",
      "Easy Installation and Maintenance",
      "Lower Cost",
    ],
    technical: [
      {
        "Flow (Q)": "4 - 10m³/hr",
        "Head (H)": "25m",
        "Working Temperature": "20°C ~ 120°C",
        "Inlet/Outlet": "40mm/40mm",
        Motor: "2hp @ 1450 / 2900 rpm",
      },
    ],
    applications: [
      "Water Supply",
      "Solid Handling in Industrial Waste Product",
      "Auxiliary Services in Chemical Industries",
      "Sewage Pumping",
      "Aggressive Liquid Applications",
      "Small Pond or Fountain",
      "Manure Handling in Agriculture",
    ],
    model: [
      "SKMS 1.5",
    ],
  },
  {
    id: 6,
    name: "SK 168 & 188D",
    image: "/skseries/ChemicalDosingPumpSK.png",
    description: "Chemical Dosing Pump",
    features: [
      "Flexibility",
      "Service-Friendly",
      "Wide Range",
      "High Accuracy",
    ],
    technical: [
      {
        "Flow (Q)": "Simplex 60 Ltr/hr, Duplex 120 Ltr/hr",
        Pressure: "Max 35kg/cm³",
        "Working Temperature": "80°C ~ 120°C",
        "Suction Lift": "Max 3mm for Water",
      },
    ],
    applications: [
      "Water Treatment",
      "Wastewater Treatment",
      "Acids",
      "Cosmetics",
      "Food Ingredients",
      "Chemical Additive",
      "Soap Lubricant",
    ],
    model: [
      "SK 168S / D",
      "SK 188S / D",
      "SK 268S / D",
      "SK 288S / D",
    ],
  },
  {
    id: 7,
    name: "SK 368 SERIES",
    image: "/skseries/ChemicalDiaphragmPumpSK368Series.png",
    description: "Chemical Diaphragm Pump",
    features: [
      "Minimal Maintenance ",
      "High Performance",
      "Low Lifecycle Cost",
      "Long Life Span",
    ],
    technical: [
      {
        "Capacity Range": "10 1ph - 1000 1ph under 50HZ",
        "Pressure Range": "2 - 10 bar",
        "Working Temperature": "30°C ~ 80°C",
        "Stoke Adjustment": "0 ~ 100%",
      },
    ],
    applications: [
      "Heavy-duty Designed Process Pump for Chemical Dosing",
      "Waste Treatment", 
      "Industrial Chemical Process", 
      "Agriculture",
    ],
    model: [
      "SK 368-120",
      "SK 368-240",
      "SK 368-400",
      "SK 368-600",
      "SK 368-1000",
    ],
  },
  {
    id: 8,
    name: "SKVSP SERIES",
    image: "/skseries/VerticalSumpPumpSKVSPSeries.png",
    description: "Vertical Sump Pump",
    features: [
      "Single Stage Centrifugal Sump Pump",
      "Transferring and Handling of Sediment, Sludge, Scale, Slurries",
      "Fully Stainless Steel Constructed for Corrosion Resistant",
      "Adjustable Submerged Dephs",
      "Double Bearing at Frame Adaptor",
    ],
    technical: [
      {
        "Flow (Q)": "Max 250m³/hr",
        "Head (H)": "Max 22m",
        "Solid Size": "Max 30mm",
        "Impeller Type": "Semi-Open",
        "Submerged Column": "1m",
        "Non-submerged Column": "0.50m",
        "Shaft": "Rigid 38mm Dynamically Balance",
        "Shaft Sleeve / Grand Packed": "Stainless Steel and Media Lubricated",
        "Bearing": "Double Bearing at Frame Adaptor",
      },
    ],
    applications: [
      "Palm Oil Mill Pit and Pond",
      "Sump drainage",
      "Food Control",
      "Power Plants",
      "Condensation control",
      "Dewatering Service",
    ],
    model: [
      "SKVSP 2.5 / 1.5",
      "SKVSP 3 / 2",
      "SKVSP 4 / 3",
      "SKVSP 5 / 4R",
    ],
  },
  {
    id: 9,
    name: "PRE-CLEANER SYSTEM",
    image: "/skseries/PreCleanerSystem.png",
    description: "SK PRE-CLEANER WITH AUTO DISCHARGE SYSTEM",
    features: [
      "Components Made in Wear Resistant Material",
      "High Abrasive Resistance Ceramic Cyclone",
      "High Efficiency of Sand Removal",
      "Negligible Starch Loss Due to Upstream Water",
      "Automatic Sand Discharge",
    ],
    technical: [
      {
        "Cyclone Diameter": "100 ~ 150mm",
        "Capacity": "15.0 ~ 30.0m³/hr",
        "Equivalent Milling Capacity": "30 ~ 60 mt  FFB/hr",
      },
    ],
    applications: [
      "Trap Sand and Particle from Different Liquid or Process Water such as Crude Palm Oil and Sludge Waster",
    ],
    model: [
      "100-30S",
      "100-30D",
      "150-45S",
      "150-60S",
    ],
  },
  {
    id: 10,
    name: "SKOSP SERIES",
    image: "/skseries/SKOSPSeries.png",
    description: "OIL SKIMMER PUMP",
    features: [
      "Simple, Proven & Dependable Design",
      "Quick & Easy Installation",
      "Self-adjusting to Changing Wastewater Level",
      "Simple & Compact Structure",
    ],
    technical: [
      {
        "Flow (Q)": "5m³/hr or 1000L/hr",
        "Priming Head": "10m",
        "Lift Head": "20m",
        "Speed": "1450 rpm",
      },
    ],
    applications: [
      "Oily Wastewater Industrial Operations",
      "Fuel Distribution Areas",
      "Chemical Processing Facilities",
      "Transportation Wash-down Sump",
    ],
    model: [
      'SKOSP 1"',
    ],
  },
  {
    id: 11,
    name: "SK MIXER SERIES",
    image: "/skseries/SKMixerSeries.png",
    description: "SK MIXER & AGITATOR",
    features: [
      "Continuous Operations is Possible",
      "Space Saving, Light Weight and Easy Installations & Maintenance",
      "Low Operations Cost",
      "Stable Performance, Low Noise and Low Vibrations",
      "Long Lift Span of Gear Motor and Support Bearing",
    ],
    technical: [
      {
        "Flow (Q)": "Low Viscosity: 1250 Ltr, Medium Viscosity: 400 Ltr",
        "Input Power": "0.37 kw/0.5 hp 415V",
        "Resolutions": "295 rpm",
        "Shaft Diameters": "16mm",
        "Impeller Diameters": "200mm",
      },
    ],
    applications: [
      "Used for rapid mixing, neutralizations in",
      "Chemical Industries",
      "Waste Water Industries",
      "Food Processing",
      "Agriculture",
    ],
    model: [
      "SK 1250",
    ],
  },
  {
    id: 12,
    name: "VC SERIES",
    image: "/skeroseries/VCSeries.png",
    description: "LIQUID RING VACUUM PUMP",
    features: [
      "Efficient Single Stage Design",
      "Low Maintenance Required",
      "Low Noise & Vibration Levels",
      "Entrained Liquid Handling",
    ],
    technical: [
      {
        "Flow (Q)": "180 ~ 600m³/hr",
        "Head (H)": 'Max 27"hg',
        "Working Temperature": "Service Liquid(80°C ~ 120°C), Gas(Max 100°C)",
        "Sealing": "Mechanical Seal",
        "Viscosity": "Max 90 mm²/s",
        "Flow Resistance of Heat Exchanger": "Max 0.2 bar",
      },
    ],
    applications: [
      "Drying",
      "Distillation",
      "Evaporation Crystallization",
      "Vapor Recovery",
      "Sterilization",
      "Filtration",
      "Vacuum Conveyance",
      "Priming",
      "Central Vacuum Systems",
    ],
    model: [
      "VC 40-160",
      "VC 50-120",
      "VC 50-160",
      "VC 50-200",
      "VC 65-200",
      "VC 65-266",
    ],
  },
  {
    id: 13,
    name: "BF SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "MULTI STAGE BOILER FEED WATER PUMP",
    features: [
      "High Efficiency",
      "Low Energy Consumption",
      "Longer Life",
      "Advanced Modular Design",
    ],
    technical: [
      {
        "Flow (Q)": "Max 110m³/hr",
        "Head (H)": "Max 395m",
        "Working Temperature": "Max 194°C",
        "Shaft Sealing": "Gland  Packing or Mechanical Seal",
        "Sense of Rotation": "Clockwise, when Viewed from Discharge Side",
      },
    ],
    applications: [
      "Boiler Feed",
      "Pressure Boosting",
      "High Pressure Cleaning",
      "Condensate Systems",
      "Chemical & Process",
      "Irrigation of Plant",
      "Heating Plant",
      "Reverse Osmosis",
      "Water Supply in High-rise Building",
    ],
    model: [
      "BF 40-",
      "BF 50-",
      "BF 65-",
    ],
  },
  {
    id: 14,
    name: "OT SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "SIDE CHANNEL OIL TRANSFER PUMP",
    features: [
      "Self-priming",
      "Gas Handling",
      "Ability to Handle Liquid Problem-free under Unfavourable Conditions",
      "Low NPSH Value",
    ],
    technical: [
      {
        "Flow (Q)": "Max 35m³/hr",
        "Head (H)": "Max 354m",
        "Speed": "Max 1800 rpm",
        "Working Temperature": "180°C",
        "Casing Pressure": "PN 40",
        "Shaft Sealing": "Gland Packing / Mechanical Seal",
        "Flange Connection": "DIN 2501 PN 40",
        "Sense of Rotation": "Anti-Clockwise",
      },
    ],
    applications: [
      "Condensate",
      "Distillation",
      "Refrigerants",
      "Oil Transfer",
      "Fuel Storage",
      "Liquid Gas",   
    ],
    model: [
      "OT 40-",
      "OT 50-",
      "OT 65-",
    ],
  },
  {
    id: 15,
    name: "DT SERIES",
    image: "/skeroseries/DTSeries.png",
    description: "VOLUTE CASING DEAERATOR PUMP",
    features: [
      "Non-clogging Design",
      "Suitable for Higher Flow per Pump",
      "Reliability & High Efficiency",
      "Simple Maintenance",
    ],
    technical: [
      {
        "Flow (Q)": "Max 110m³/hr",
        "Head (H)": "Max 395m",
        "Speed": "Max 3000 rpm",
        "Working Temperature": "120°C",
        "Casing Pressure": "PN 16/10",
        "Shaft Sealing": "Mechanical Seal",
        "Flange Connection": "DIN 2501 PN 16/10",
        "Sense of Rotation": "Clockwise, when Viewed from the Driver End",
      },
    ],
    applications: [
      "Drinking Water Supply for Communities",
      "General Water Supply in Agriculture, Business & Industry",
      "Draining of Tanks & Reservoirs",
      "Irrigation, sprinking & drainage systems",
      "Condense Water Pumping",
      "Petrochemical Sector",
      "Handling Crude Oil & Refinery Intermediates",
    ],
    model: [
      "DT 65-250",
      "DT 80-250",
    ],
  },
  {
    id: 16,
    name: "WOLTMAN FLOWMETER",
    image: "/setech/WoltmanFlowmeter.png",
    description: "COLD WATER HORIZONTAL WOLTMAN FLOWMETER",
    features: [
      "Easy Installation and Maintenance",
      "Dry-dial, Magnetic Drive Sensitive Action, Small Pressure Loss",
      "Vacuum Sealed Register, Free from Fog and Clear Reading",
      "High Quality Materials",
      "International Standard ISO 4064",
    ],
    technical: [
      {
        "Working Temperature": "0.1°C ~ 40°C, Hot Water Meter(0.1°C ~ 90°C)",
        "Water Pressure": "≤ 1.6Mpa",
        "Maximum Permissible Errors": "Lower Zone from qmin inclusive up to but excluding qt is ±5%, Upper Zone from qt inclusive up to and including qs is ±2% (±3% for Hot Water Meter)",
      },
    ],
    applications: [
      "Measuring the Volume of Cold/Hot Waterpassing through the Pipeline",
    ],
    model: [
      "HGLC-50",
      "HGLC-65",
      "HGLC-80",
      "HGLC-100",
      "HGLC-125",
      "HGLC-150",
      "HGLC-200",
      "HGLC-250",
      "HGLC-300",
    ],
  },
  {
    id: 17,
    name: "ELECTROMAGNETIC FLOWMETER",
    image: "/setech/ElectromagneticFlowmeter.png",
    description: "ELECTROMAGNETIC FLOWMETER",
    features: [
      "Long Operation Life",
      "No Intercepting Fluid Parts",
      "No Pressure Loss and Fluid Clogging",
      "Adopt EEPROM Memory",
      "Integral Type Flow Meters & Remote Type Flow Meters",
      "LCD Back Light Display",
      "Bi-direction Measurement (Option)",
      'Aproved from CE, EMC, ISO',
      'Programming Language: English',
    ],
    technical: [
      {
        "Suitable Diameter": "DN25 ~ DN2600 (below DN25 Non-standard)",
        "Electrode No.": "2 ~ 3pcs",
        "Min Conductivity": "More than 5 Microsimens",
        "Measuring Range": "0.5 ~ 10m/s (extendable to 15m/s)",
        "Upper Limit of Span": "0.5 ~ 10m/s, 1 ~ 5m/s Recommended ",
        "Accuracy": "0.3%(Option), 0.5%, 1.0% of F.S.",
        "Repeatability": "Below 0.25%",
        'Power Consumption': "≤ 8W",
        'Operation Pressure': '1.0MPa, 1.6MPa, 4.0MPa, 16Mpa(Special)',
        'Fluid Temperature': "-20°C ~ 80°C, 80°C ~ 130°C, 130°C ~ 180°C Depending on Lining Material",
        'Quality Control': 'ISO9001-2008, CE',
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SE-HGD-15 ",
      "SE-HGD-20 ",
      "SE-HGD-25 ",
      "SE-HGD-32 ",
      "SE-HGD-40 ",
      "SE-HGD-50 ",
      "SE-HGD-65 ",
      "SE-HGD-80 ",
      "SE-HGD-100 ",
      "SE-HGD-125 ",
      "SE-HGD-150 ",
      "SE-HGD-200 ",
      "SE-HGD-250 ",
      "SE-HGD-300 ",
      "SE-HGD-350 ",
      "SE-HGD-400 ",
      "SE-HGD-450",
      "SE-HGD-500",
      "SE-HGD-600",
      "SE-HGD-700",
      "SE-HGD-800",
      "SE-HGD-1000",
      "SE-HGD-1200",
      "SE-HGD-1400",
      "SE-HGD-1600",
      "SE-HGD-1800",
      "SE-HGD-2000",
      "SE-HGD-2200",
      "SE-HGD-2400",
      "SE-HGD-2600",
    ],
  },
  {
    id: 18,
    name: "FLOWMETER CONTROLLER",
    image: "/setech/FlowmeterController.png",
    description: "FLOWMETER CONTROLLER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 19,
    name: "NUT CRACKER",
    image: "/setech/NutCracker.png",
    description: "NUT CRACKER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Capacity": "8mt/hr",
        "Rotor Support": "Heavy Duty Plummer Block Bearing at Both Ends",
        "Motor": "20Hp(15kw) 380-420v/3ph/50Hz/4pole Foot Mounted",
        "Drive": 'SPB 3 x7" and 11" Taper Lock Pulley and Belting c/w Belting Cover',
        "Base Frame": "50 x 100mm Channel",
        "Performance" : "Cracking Efficiency of > 98%",
      },
    ],
    applications: [
      "Palm Oil",
    ],
    model: [
      "SE-8MT",
    ],
  },
  {
    id: 20,
    name: "GAS DETECTOR",
    image: "/setech/GasDetector.png",
    description: "GAS DETECTOR",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 21,
    name: "ULTRASONIC THICKNESS GAUG",
    image: "/setech/UltrasonicGauge.png",
    description: "ULTRASONIC THICKNESS GAUG",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 22,
    name: "CONVEYOR CHAIN",
    image: "/trp/PalmOilChain.png",
    description: "CONVEYOR CHAIN",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Breaking Load (SIRIM Test)": "SOLID Pin Chain(44000 ~ 81000lbf), HOLLOW Pin Chain(27000 ~ 59000lbf)",
        "Pitch(P)": "101.60mm & 152.40mm",
        "Roller Diameter(D)": "47.60mm & 66.70mm",
        "Pin Diameter(D)": "SOLID Pin Chain(19.00mm & 27.00mm), HOLLOW Pin Chain(13.20mm & 20.10mm)",
        "Plate Height": "38.10mm & 50.80mm",
      },
    ],
    applications: [
      "Palm Oil Industry",
    ],
    model: [
      "Solid Pin Chain (SPC)",
      "TRP SM220040",
      "TRP SM400060",
      "TRP SM600060",
      "Hollow Pin Chain (HPC)",
      "TRP HM200040",
      "Trp HM360060",
      "Trp HM500060",
    ]
  },
  {
    id: 23,
    name: "SPROCKETS",
    image: "/trp/Sprockets.png",
    description: "SPROCKETS",
    features: [
      "Realiability",
    ],
    technical: [
      {
        "Material": "Cast Iron / Cast Steel",
        "No. of Teeth": "8 ~ 21",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Palm Oil Industry",
    ],
    model: [
      "Chain Pitch 101.6",
      "Chain Pitch 152.4",
    ],
  },
  {
    id: 24,
    name: "MC SERIES",
    image: "/seweurodrive/MCSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 25,
    name: "M SERIES",
    image: "/seweurodrive/MSeries.png",
    description: "KERNEL EXPELLER DRIVES & EFB PRESS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 26,
    name: "CN SERIES",
    image: "/seweurodrive/CNSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 27,
    name: "R SERIES",
    image: "/seweurodrive/RSeries.png",
    description: "HELICAL GEAR MOTORS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 28,
    name: "M SERIES SCREW PRESS DRIVE",
    image: "/seweurodrive/MSeriesScrew.png",
    description: "SCREW PRESS DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 29,
    name: "BALL VALVE",
    image: "/valve/BallValve3.png",
    description: "1PC / 3PC BODY BALL VALVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow (Q)": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
];
