export const products = [
  {
    id: 1,
    name: "SK & SKL Series",
    image: "/skseries/Skseries.png",
    description: "End Suction Centrifugal Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 270m³/hr",
        "Head (H)": "Max 102m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SK 3 / 2",
      "SK 4 / 3",
      "SKB 6 / 4",
      "SKL 2.5 / 1.5",
      "SKL 3 / 2",
      "SKL 4 / 3",
      "SKL 6 / 4",
    ],
  },
  {
    id: 2,
    name: "SKP SERIES",
    image: "/skseries/Skpseries.png",
    description: "Self-Priming Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 210m³/hr",
        "Head (H)": "Max 90m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "3 Pump Sizes",
      },
    ],
    applications: [
      "Waste Water",
      "Water Supply",
      "Fuel, Diesel & Light Oils",
    ],
    model: [
      "SKP 1.5",
      "SKP 2",
      "SKP 3",
    ],
  },
  {
    id: 3,
    name: "SKLB SERIES",
    image: "/skseries/Sklwseries.png",
    description: "Desander Centrifugal Pump",
    features: [
      "Handle Abrasive and Corrosive Pulp with Heavy Slurries",
      "Low Speed",
      "Hydraulic Design",
      "Interchangeability",
      "Heavy Duty Construction",
      "Low Operating Cost",
    ],
    technical: [
      {
        "Flow Q": "Max 110m³/hr",
        "Head (H)": "Max 60m",
        "Working Temperature": "80°C ~ 120°C",
        Bearing: "Heavy duty pedestal / Big bearing",
        "Impeller Diameter": "380mm - 'Closed' Type",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Contain",
      },
    ],
    applications: [
      "Feed Pump in Pre-Cleaner System",
      "Cleaning System for Oil and Gas Industries",
      "Sludge Thickening and Dewatering",
      "Waste Treatment",
      "Food and Chemical Industries",
      "Crude Palm Oil Industries",
    ],
    model: [
      "SKLB 40-380C",
    ],
  },
  {
    id: 4,
    name: "SKWT SERIES",
    image: "/skseries/Skwtseries.png",
    description: "End Suction Centrifugal Pump",
    features: [
      "Optimized hydraulics",
      "Easy maintenance",
      "Wide range",
      "High efficiency & reliability",
    ],
    technical: [
      {
        "Flow Q": "Max 480m³/hr @2900rpm",
        "Head (H)": "Max 100m @2900rpm/ Max45 @1450rpm",
        "Working Temperature": "95°C",
        Connection: "Flange(PN16)",
        Rotation: "Clockwise",
        Material: "Cast Iron / Stainless Steel 304 / 316",
      },
    ],
    applications: [
      "Raw Water Supply",
      "Drainage",
      "Pumping",
      "Heating & Ventilating",
      "Fire Fighting",
      "Water Treatment & Supply",
    ],
    model: [
      "SKWT 32-130 ~ 100-400",
    ],
  },
  {
    id: 5,
    name: "SKMS SERIES",
    image: "/skseries/SKMSseries.png",
    description: "Closed Coupled, Small Centrifugal Pump",
    features: [
      "Light Weight and Compact",
      "Safety and Reliable Operation",
      "Easy Installation and Maintenance",
      "Lower Cost",
    ],
    technical: [
      {
        "Flow Q": "4 - 10m³/hr",
        "Head (H)": "25m",
        "Working Temperature": "20°C ~ 120°C",
        "Inlet/Outlet": "40mm/40mm",
        Motor: "2hp @ 1450 / 2900 rpm",
      },
    ],
    applications: [
      "Water Supply",
      "Solid Handling in Industrial Waste Product",
      "Auxiliary Services in Chemical Industries",
      "Sewage Pumping",
      "Aggressive Liquid Applications",
      "Small Pond or Fountain",
      "Manure Handling in Agriculture",
    ],
    model: [
      "SKMS 1.5",
    ],
  },
  {
    id: 6,
    name: "SK 168 & 188D",
    image: "/skseries/ChemicalDosingPumpSK.png",
    description: "Chemical Dosing Pump",
    features: [
      "Flexibility",
      "Service-Friendly",
      "Wide Range",
      "High Accuracy",
    ],
    technical: [
      {
        "Flow (Q)": "Simplex 60 Ltr/hr, Duplex 120 Ltr/hr",
        Pressure: "Max 35kg/cm³",
        "Working Temperature": "80°C ~ 120°C",
        "Suction Lift": "Max 3mm for Water",
      },
    ],
    applications: [
      "Water Treatment",
      "Wastewater Treatment",
      "Acids",
      "Cosmetics",
      "Food Ingredients",
      "Chemical Additive",
      "Soap Lubricant",
    ],
    model: [
      "SK 168S / D",
      "SK 188S / D",
      "SK 268S / D",
      "SK 288S / D",
    ],
  },
  {
    id: 7,
    name: "SK 368 SERIES",
    image: "/skseries/ChemicalDiaphragmPumpSK368Series.png",
    description: "Chemical Diaphragm Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 8,
    name: "SKVSP SERIES",
    image: "/skseries/VerticalSumpPumpSKVSPSeries.png",
    description: "Vertical Sump Pump",
    features: [
      "Single Stage Centrifugal Sump Pump",
      "Transferring and Handling of Sediment, Sludge, Scale, Slurries",
      "Fully Stainless Steel Constructed for Corrosion Resistant",
      "Adjustable Submerged Dephs",
      "Double Bearing at Frame Adaptor",
    ],
    technical: [
      {
        "Flow Q": "Max 250m³/hr",
        "Head (H)": "Max 22m",
        "Solid Size": "Max 30mm",
        "Impeller Type": "Semi-Open",
        "Submerged Column": "1m",
        "Non-submerged Column": "0.50m",
        "Shaft": "Rigid 38mm Dynamically Balance",
        "Shaft Sleeve / Grand Packed": "Stainless Steel and Media Lubricated",
        "Bearing": "Double Bearing at Frame Adaptor",
      },
    ],
    applications: [
      "Palm Oil Mill Pit and Pond",
      "Sump drainage",
      "Food Control",
      "Power Plants",
      "Condensation control",
      "Dewatering Service",
    ],
    model: [
      "SKVSP 2.5 / 1.5",
      "SKVSP 3 / 2",
      "SKVSP 4 / 3",
      "SKVSP 5 / 4R",
    ],
  },
  {
    id: 9,
    name: "PRE-CLEANER SYSTEM",
    image: "/skseries/PreCleanerSystem.png",
    description: "SK PRE-CLEANER WITH AUTO DISCHARGE SYSTEM",
    features: [
      "Components Made in Wear Resistant Material",
      "High Abrasive Resistance Ceramic Cyclone",
      "High Efficiency of Sand Removal",
      "Negligible Starch Loss Due to Upstream Water",
      "Automatic Sand Discharge",
    ],
    technical: [
      {
        "Cyclone Diameter": "100 ~ 150mm",
        "Capacity": "15.0 ~ 30.0m³/hr",
        "Equivalent Milling Capacity": "30 ~ 60 mt  FFB/hr",
      },
    ],
    applications: [
      "Trap Sand and Particle from Different Liquid or Process Water such as Crude Palm Oil and Sludge Waster",
    ],
    model: [
      "100-30S",
      "100-30D",
      "150-45S",
      "150-60S",
    ],
  },
  {
    id: 10,
    name: "SKOSP SERIES",
    image: "/skseries/SKOSPSeries.png",
    description: "OIL SKIMMER PUMP",
    features: [
      "Simple, Proven & Dependable Design",
      "Quick & Easy Installation",
      "Self-adjusting to Changing Wastewater Level",
      "Simple & Compact Structure",
    ],
    technical: [
      {
        "Flow Q": "5m³/hr or 1000L/hr",
        "Priming Head": "10m",
        "Lift Head": "20m",
        "Speed": "1450 rpm",
      },
    ],
    applications: [
      "Oily Wastewater Industrial Operations",
      "Fuel Distribution Areas",
      "Chemical Processing Facilities",
      "Transportation Wash-down Sump",
    ],
    model: [
      'SKOSP 1"',
    ],
  },
  {
    id: 11,
    name: "SK MIXER SERIES",
    image: "/skseries/SKMixerSeries.png",
    description: "SK MIXER & AGITATOR",
    features: [
      "Continuous Operations is Possible",
      "Space Saving, Light Weight and Easy Installations & Maintenance",
      "Low Operations Cost",
      "Stable Performance, Low Noise and Low Vibrations",
      "Long Lift Span of Gear Motor and Support Bearing",
    ],
    technical: [
      {
        "Flow Q": "Low Viscosity: 1250 Ltr, Medium Viscosity: 400 Ltr",
        "Input Power": "0.37 kw/0.5 hp 415V",
        "Resolutions": "295 rpm",
        "Shaft Diameters": "16mm",
        "Impeller Diameters": "200mm",
      },
    ],
    applications: [
      "Used for rapid mixing, neutralizations in",
      "Chemical Industries",
      "Waste Water Industries",
      "Food Processing",
      "Agriculture",
    ],
    model: [
      "SK 1250",
    ],
  },
  {
    id: 12,
    name: "VC SERIES",
    image: "/skeroseries/VCSeries.png",
    description: "LIQUID RING VACUUM PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 13,
    name: "BF SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "MULTI STAGE BOILER FEED WATER PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 14,
    name: "OT SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "SIDE CHANNEL OIL TRANSFER PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 15,
    name: "DT SERIES",
    image: "/skeroseries/DTSeries.png",
    description: "VOLUTE CASING DEAERATOR PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 16,
    name: "WOLTMAN FLOWMETER",
    image: "/setech/WoltmanFlowmeter.png",
    description: "COLD WATER HORIZONTAL WOLTMAN FLOWMETER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 17,
    name: "ELECTROMAGNETIC FLOWMETER",
    image: "/setech/ElectromagneticFlowmeter.png",
    description: "ELECTROMAGNETIC FLOWMETER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 18,
    name: "FLOWMETER CONTROLLER",
    image: "/setech/FlowmeterController.png",
    description: "FLOWMETER CONTROLLER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 19,
    name: "NUT CRACKER",
    image: "/setech/NutCracker.png",
    description: "NUT CRACKER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 20,
    name: "GAS DETECTOR",
    image: "/setech/GasDetector.png",
    description: "GAS DETECTOR",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 21,
    name: "ULTRASONIC THICKNESS GAUG",
    image: "/setech/UltrasonicGauge.png",
    description: "ULTRASONIC THICKNESS GAUG",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 22,
    name: "CONVEYOR CHAIN",
    image: "/trp/PalmOilChain.png",
    description: "CONVEYOR CHAIN",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 23,
    name: "SPROCKETS",
    image: "/trp/Sprockets.png",
    description: "SPROCKETS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 24,
    name: "MC SERIES",
    image: "/seweurodrive/MCSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 25,
    name: "M SERIES",
    image: "/seweurodrive/MSeries.png",
    description: "KERNEL EXPELLER DRIVES & EFB PRESS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 26,
    name: "CN SERIES",
    image: "/seweurodrive/CNSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 27,
    name: "R SERIES",
    image: "/seweurodrive/RSeries.png",
    description: "HELICAL GEAR MOTORS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 28,
    name: "M SERIES SCREW PRESS DRIVE",
    image: "/seweurodrive/MSeriesScrew.png",
    description: "SCREW PRESS DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 29,
    name: "BALL VALVE",
    image: "/valve/BallValve3.png",
    description: "1PC / 3PC BODY BALL VALVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        "Flow Q": "Max 400m³/hr",
        "Head (H)": "Max 100m",
        "Working Temperature": "80°C ~ 120°C",
        Sizes: "9 Pump Sizes",
        "Solid Handling Capacity": "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
];
