export const products = [
  // {
  //   "id": 1,
  //   "name": "BALL VALVE",
  //   "brand": "VALVE",
  //   "alt": "1PC / 3PC BODY BALL VALVE",
  //   "image": "/valve/BallValve3.png",
  //   "productTab": "1",
  // },
  {
    "id": 2,
    "name": "GLOVE VALVE",
    "brand": "VALVE",
    "alt": "CAST IRON CAST STEEL FLANGE END",
    "image": "/valve/GloveValve.png",
    "productTab": "1",
  },
  {
    "id": 3,
    "name": "BUTTERFLY VALVE DISC",
    "brand": "VALVE",
    "alt": "CAST IRON / STAINLESS STEEL",
    "image": "/valve/ButterflyValve.png",
    "productTab": "1",
  },
  {
    "id": 4,
    "name": "BLOW DOWN VALVE",
    "brand": "VALVE",
    "alt": "BLOW DOWN VALVE",
    "image": "/valve/BlowDownValve.png",
    "productTab": "1",
  },
  {
    "id": 5,
    "name": "NEEDLE VALVE 316",
    "brand": "VALVE",
    "alt": "STAINLESS STEEL / CARBON STEEL",
    "image": "/valve/NeedleValve.png",
    "productTab": "1",
  },

  {
    "id": 1,
    "name": "SINGLE DOORSWING",
    "brand": "CHECK VALVE",
    "alt": "WAFER TYPE CHECK VALVE",
    "image": "/checkvalve/SingleDoorSwing.png",
    "productTab": "2",
  },
  {
    "id": 2,
    "name": "DUAL PLATE",
    "alt": "CAST IRON CHECK VALVE",
    "brand": "CHECK VALVE",
    "image": "/checkvalve/DualPlate.png",
    "productTab": "2",
  },
  {
    "id": 3,
    "name": "SWING CHECK VALVE",
    "brand": "CHECK VALVE",
    "alt": "STAINLESS STEEL 10K/150LBS FLANGE END PN16",
    "image": "/checkvalve/Swing.png",
    "productTab": "2",
  },
  {
    "id": 4,
    "name": "LIFT CHECK VALVE",
    "brand": "CHECK VALVE",
    "alt": "CAST STEEL PN16/PN40",
    "image": "/checkvalve/Lift.png",
    "productTab": "2",
  },
  {
    "id": 5,
    "name": "DISCO CHECK VALVE",
    "brand": "CHECK VALVE",
    "alt": "STAINLESS STEEL WAFER TYPE",
    "image": "/checkvalve/Disco.png",
    "productTab": "2",
  },

  {
    "id": 1,
    "name": "TITANIUM PUTTY",
    "brand": "COATING",
    "alt": "TITANIUM PUTTY",
    "image": "/coating/TitaniumPutty.png",
    "productTab": "3",
  },
  {
    "id": 2,
    "name": "THERMAL COAT",
    "brand": "COATING",
    "alt": "THERMAL COAT",
    "image": "/coating/ThermalCoat.png",
    "productTab": "3",
  },
  {
    "id": 3,
    "name": "CERAMIC COAT",
    "brand": "COATING",
    "alt": "CERAMIC COAT",
    "image": "/coating/CeramicCoat.png",
    "productTab": "3",
  },
  {
    "id": 4,
    "name": "CERAMIC PUTTY",
    "brand": "COATING",
    "alt": "CERAMIC PUTTY",
    "image": "/coating/CeramicPutty.png",
    "productTab": "3",
  },
  {
    "id": 5,
    "name": "CORRO TEMP 700",
    "brand": "COATING",
    "alt": "CORRO TEMP 700",
    "image": "/coating/CorroTemp.png",
    "productTab": "3",
  },

  {
    "id": 1,
    "name": "SIHI MSLA CAST IRON",
    "brand": "BEARING HOUSING",
    "alt": "SIHI MSLA CAST IRON",
    "image": "/bearing/SihiMsla.png",
    "productTab": "4",
  },
  {
    "id": 2,
    "name": "ES SPECK",
    "brand": "BEARING HOUSING",
    "alt": "ES SPECK",
    "image": "/bearing/EsSpeck.png",
    "productTab": "4",
  },
  {
    "id": 3,
    "name": "SK",
    "brand": "BEARING HOUSING",
    "alt": "SK",
    "image": "/bearing/Sk.png",
    "productTab": "4",
  },
  {
    "id": 1,
    "name": "ULYSSES PUMP",
    "brand": "IMPELLER",
    "alt": "ULYSSES PUMP",
    "image": "/impeller/Ulysses.png",
    "productTab": "5",
  },
  {
    "id": 2,
    "name": "SOUTHERN CROSS",
    "brand": "IMPELLER",
    "alt": "SOUTHERN CROSS CAST IRON /STAINLESS STEEL PUMP",
    "image": "/impeller/SouthernCross.png",
    "productTab": "5",
  },
  {
    "id": 3,
    "name": "SAMSON",
    "brand": "IMPELLER",
    "alt": "SAMSON AM / CAST IRON / TRQ PUMP",
    "image": "/impeller/Samson.png",
    "productTab": "5",
  },
  {
    "id": 4,
    "name": "MTP",
    "brand": "IMPELLER",
    "alt": "ASC / SH / SHPC / MSCC / MSSC / OB3 / OB4 / OBNT OB / OBSH PUMP",
    "image": "/impeller/Mtp.png",
    "productTab": "5",
  },
  {
    "id": 5,
    "name": "SIHI",
    "brand": "IMPELLER",
    "alt": "SIHI CAST IRON / SIHI ULNC / SIHI CEHA / VANE / DIFFUSER SIHI HEGA / SIHI MSLA PUMP",
    "image": "/impeller/Sihi.png",
    "productTab": "5",
  },
  {
    "id": 6,
    "name": "KEWPUMP",
    "brand": "IMPELLER",
    "alt": "KEWPUMP",
    "image": "/impeller/Kewpump.png",
    "productTab": "5",
  },
  {
    "id": 1,
    "name": "MTP",
    "brand": "SEAL HOUSING",
    "alt": "MTP SEAL HOUSING STAINLESS STEEL CMA",
    "image": "/sealhousing/MTP.png",
    "productTab": "6",
  },
  {
    "id": 2,
    "name": "SAMSON",
    "brand": "SEAL HOUSING",
    "alt": "SAMSON SEAL HOUSING STAINLESS STEEL CMA",
    "image": "/sealhousing/Samson.png",
    "productTab": "6",
  },
  {
    "id": 1,
    "name": "SIHI",
    "brand": "SHAFT",
    "alt": "SIHI CEHA, SIHI ULNC, SIHI MSLA, SIHI LPHA & LPHS",
    "image": "/shaft/SIHI.png",
    "productTab": "7",
  },
  {
    "id": 2,
    "name": "MTP",
    "brand": "SHAFT",
    "alt": "MSC & MSSC(GRAND), SHAFT FOR OBNT (GRANT/SEAL)",
    "image": "/shaft/MTP.png",
    "productTab": "7",
  },
  {
    "id": 3,
    "name": "KEWPUMP",
    "brand": "SHAFT",
    "alt": "STAINLESS STEEL SHAFT",
    "image": "/shaft/Kewpump.png",
    "productTab": "7",
  },
  {
    "id": 4,
    "name": "OTHERS",
    "brand": "SHAFT",
    "alt": "SAMSON, TRQ, ALLEN GWYNESS, ES SPECK, SOUTHERN CROSS, ULYSSES",
    "image": "/shaft/Others.png",
    "productTab": "7",
  },
  {
    "id": 1,
    "name": "SIHI",
    "brand": "SHAFT SLEEVE",
    "alt": "SIHI CEHA, SIHI HEGA, SIHI MSLA",
    "image": "/shaftSleeve/SIHI.png",
    "productTab": "8",
  },
  {
    "id": 2,
    "name": "SPECK",
    "brand": "SHAFT SLEEVE",
    "alt": "SPECK",
    "image": "/shaftSleeve/Speck.png",
    "productTab": "8",
  },
  {
    "id": 1,
    "name": "RECORDING CHART",
    "brand": "RECORDING CHART",
    "alt": "RECORDING CHART PAPER",
    "image": "/recordingChart/chart.png",
    "productTab": "9",
  },
  {
    "id": 1,
    "name": "LEVEL GAUGE COCK & PLAIN VALVE",
    "brand": "BOILER",
    "alt": "LEVEL GAUGE COCK FOR 3/4' ANSI 300RF TOP & BOTTOM COCK + PLAIN VALVE",
    "image": "/boiler/gaugeCock.png",
    "productTab": "10",
  },
  {
    "id": 2,
    "name": "LEVEL GAUGE A9",
    "brand": "BOILER",
    "alt": "LEVEL GAUGE A9 SINGLE BODY REFLEX GLASS",
    "image": "/boiler/gaugeA9.png",
    "productTab": "10",
  },
  {
    "id": 3,
    "name": "LEVEL GAUGE BY B9",
    "brand": "BOILER",
    "alt": "LEVEL GAUGE BY B9 3PC BODY TRANSPARENT GLASS",
    "image": "/boiler/gaugeB9.png",
    "productTab": "10",
  },
  {
    "id": 4,
    "name": "PACKING SLEEVE",
    "brand": "BOILER",
    "alt": "PACKING SLEEVE",
    "image": "/boiler/packingSleeve.png",
    "productTab": "10",
  },
  {
    "id": 5,
    "name": "FIRE BRICK",
    "brand": "BOILER",
    "alt": "FIRE BRICK",
    "image": "/boiler/fireBrick.png",
    "productTab": "10",
  },
  {
    "id": 6,
    "name": "FIRE DOOR",
    "brand": "BOILER",
    "alt": "FIRE DOOR",
    "image": "/boiler/fireDoor.png",
    "productTab": "10",
  },
  {
    "id": 7,
    "name": "DUST COLLECTOR",
    "brand": "BOILER",
    "alt": "DUST COLLECTOR",
    "image": "/boiler/dustCollector.png",
    "productTab": "10",
  },
  {
    "id": 8,
    "name": "FIRE BAR",
    "brand": "BOILER",
    "alt": "FIRE BAR",
    "image": "/boiler/fireBar.png",
    "productTab": "10",
  },
  {
    "id": 1,
    "name": "MECHANICAL SEAL",
    "brand": "MECHANICAL SEAL",
    "alt": "SILICON, CARBON CERAMIC, SIHI CEHA, TRQ, SOUTHERN CROSS, LPHA/LPHX",
    "image": "/mechanicalSeal/mechanicalSeal.png",
    "productTab": "11",
  },
  {
    "id": 1,
    "name": "EXPELLER ARM",
    "brand": "DIGESTER",
    "alt": "EXPELLER ARM",
    "image": "/digester/expellerArm.png",
    "productTab": "12",
  },
  {
    "id": 2,
    "name": "LONG SHORT ARM",
    "brand": "DIGESTER",
    "alt": "LONG SHORT ARM",
    "image": "/digester/longShotArm.png",
    "productTab": "12",
  },
  {
    "id": 3,
    "name": "DIGESTER SLEEVE WY",
    "brand": "DIGESTER",
    "alt": "DIGESTER SLEEVE WY",
    "image": "/digester/digesterSleeveWY.png",
    "productTab": "12",
  },
  {
    "id": 4,
    "name": "BRONZE BUSH PIN",
    "brand": "DIGESTER",
    "alt": "BRONZE BUSH PIN",
    "image": "/digester/bronzeBushPin.png",
    "productTab": "12",
  },
  {
    "id": 5,
    "name": "DIGESTER PIN",
    "brand": "DIGESTER",
    "alt": "DIGESTER PIN",
    "image": "/digester/digesterPin.png",
    "productTab": "12",
  },
  {
    "id": 6,
    "name": "CASTABLE ECOKAST",
    "brand": "DIGESTER",
    "alt": "CASTABLE ECOKAST",
    "image": "/digester/castableEcoKast.png",
    "productTab": "12",
  },
  {
    "id": 1,
    "name": "WESFALIA TOP CYLINDER",
    "brand": "DESANDER",
    "alt": "WESFALIA TOP CYLINDER WF80",
    "image": "/desander/wesfaliaTopCylinder.png",
    "productTab": "13",
  },
  {
    "id": 2,
    "name": "ALPHALAVALA",
    "brand": "DESANDER",
    "alt": "ALPHALAVALA",
    "image": "/desander/alphalaval.png",
    "productTab": "13",
  },
  {
    "id": 3,
    "name": "DESANDER CONE",
    "brand": "DESANDER",
    "alt": "DESANDER CONE",
    "image": "/desander/desanderCone.png",
    "productTab": "13",
  },
  {
    "id": 1,
    "name": "PRESS CAGE",
    "brand": "SCREW PRESS",
    "alt": "PRESS CAGE",
    "image": "/screwPress/pressCage.png",
    "productTab": "14",
  },
  {
    "id": 2,
    "name": "SPIDER COUPLING",
    "brand": "SCREW PRESS",
    "alt": "SPIDER COUPLING",
    "image": "/screwPress/spiderCoupling.png",
    "productTab": "14",
  },
  {
    "id": 3,
    "name": "MAIN SHAFT",
    "brand": "SCREW PRESS",
    "alt": "MAIN SHAFT",
    "image": "/screwPress/mainShaft.png",
    "productTab": "14",
  },
  {
    "id": 4,
    "name": "WORM SCREW",
    "brand": "SCREW PRESS",
    "alt": "WORM SCREW",
    "image": "/screwPress/wormScrew.png",
    "productTab": "14",
  },
  {
    "id": 1,
    "name": "BODY DECK",
    "brand": "VIBRATING SCREEN",
    "alt": "BODY DECK",
    "image": "/vibratingScreen/bodyDeck.png",
    "productTab": "15",
  },
  {
    "id": 2,
    "name": "VIBRATING SCREEN",
    "brand": "VIBRATING SCREEN",
    "alt": "VIBRATING SCREEN",
    "image": "/vibratingScreen/vibratingScreen.png",
    "productTab": "15",
  },
  {
    "id": 1,
    "name": "CHAIN COUPLING",
    "brand": "COUPLING",
    "alt": "CHAIN COUPLING",
    "image": "/coupling/chainCoupling.png",
    "productTab": "16",
  },
  {
    "id": 2,
    "name": "FLEXIBLE COUPLING",
    "brand": "COUPLING",
    "alt": "FLEXIBLE COUPLING",
    "image": "/coupling/flexibleCoupling.png",
    "productTab": "16",
  },
  {
    "id": 3,
    "name": "TYRE ELEMENT",
    "brand": "COUPLING",
    "alt": "TYRE ELEMENT",
    "image": "/coupling/tyreElement.png",
    "productTab": "16",
  }
];